### ISSUE TITLE
Error in create_train_data.py

### ISSUE THREAD

**Issue by hmmhmmhm** [dominhhai/captcha-breaker#2]
```bash
H:\Private#2019\>python src/create_train_data.py
1 4.jpg 892851
Traceback (most recent call last):
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\arraypad.py", line 1036, in _normalize_shape
    shape_arr = np.broadcast_to(shape_arr, (ndims, 2))
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\stride_tricks.py", line 173, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\stride_tricks.py", line 128, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C').itviews[0]
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (3,2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/create_train_data.py", line 30, in <module>
    letters = split_letters(image, debug=True)
  File "H:\Private#2019\Project\article-glow\captcha-breaker\src\img.py", line 20, in split_letters
    left = crop(image, ((0, 0), (0, image.shape[1]-SHIFT_PIXEL)), copy=True)
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\skimage\util\arraycrop.py", line 172, in crop
    crops = _validate_lengths(ar, crop_width)
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\arraypad.py", line 1080, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "C:\Users\hm\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\arraypad.py", line 1039, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((0, 0), (0, 110))
```
Python 3.5.2

**Comment by vojthor** [comment]
Hi, any luck with fixing that?

**Comment by hmmhmmhm** [comment]
Nope. I have no idea in this issue.

**Comment by rodrigogs** [comment]
Same here

**Comment by christiansaiki** [comment]
Same issue here
```
python src/create_train_data.py
1 captcha9.png C7ZAS
Traceback (most recent call last):
  File "src/create_train_data.py", line 30, in <module>
    letters = split_letters(image, debug=True)
  File "/Users/chris/development/captcha-breaker/src/img.py", line 20, in split_letters
    left = crop(image, ((0, 0), (0, image.shape[1]-SHIFT_PIXEL)), copy=True)
  File "/usr/local/lib/python2.7/site-packages/skimage/util/arraycrop.py", line 172, in crop
    crops = _validate_lengths(ar, crop_width)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1080, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/arraypad.py", line 1039, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((0, 0), (0, 170))
```

**Comment by hmmhmmhm** [comment]
Good
