### ISSUE TITLE
I cant make it work

### ISSUE THREAD

**Issue by rodrigogs** [dominhhai/captcha-breaker#3]
After a long way resolving dependency issues:
```
(py3) C:\Users\rodri\Workspace\captcha-breaker>python src\create_train_data.py
C:\Users\rodri\Workspace\captcha-breaker\src\data\captcha.json
C:\Users\rodri\Workspace\captcha-breaker\src\data\captcha
C:\Users\rodri\Workspace\captcha-breaker\src\data\train
C:\Users\rodri\Workspace\captcha-breaker\src\data\captcha
1 0.png Td1Rc9
Traceback (most recent call last):
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\numpy\lib\arraypad.py", line 1036, in _normalize_shape
    shape_arr = np.broadcast_to(shape_arr, (ndims, 2))
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\numpy\lib\stride_tricks.py", line 173, in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\numpy\lib\stride_tricks.py", line 128, in _broadcast_to
    op_flags=[op_flag], itershape=shape, order='C').itviews[0]
ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,2) and requested shape (3,2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\create_train_data.py", line 36, in <module>
    letters = split_letters(image, debug=True)
  File "C:\Users\rodri\Workspace\captcha-breaker\src\img.py", line 20, in split_letters
    left = crop(image, ((0, 0), (0, image.shape[1]-SHIFT_PIXEL)), copy=True)
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\skimage\util\arraycrop.py", line 172, in crop
    crops = _validate_lengths(ar, crop_width)
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\numpy\lib\arraypad.py", line 1080, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "C:\Users\rodri\.conda\envs\py3\lib\site-packages\numpy\lib\arraypad.py", line 1039, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((0, 0), (0, 170))
```

Any idea how to fix that?

**Comment by rodrigogs** [comment]
Got it working by adding:

create_train_data.py, line: 29
```python
    image_file = Image.open(os.path.join(DATA_FULL_DIR, fname)) # open colour image
    image_file = image_file.convert('1') # convert image to black and white
    image_file.save(os.path.join(DATA_FULL_DIR, 'bw', fname))

    image = io.imread(os.path.join(DATA_FULL_DIR, 'bw', fname))
```
The cpathca image must be pure black and white, grayscale or colored images will always fail.

**Comment by joneldiablo** [comment]
works with png files?

**Comment by rodrigogs** [comment]
> works with png files?

Oh man, it's been more than two years since I don't toy around with it anymore hahahaha

But If it does not work with png, it should be easy to convert the images to a proper format beforehand.
